# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
## By starting with 1 and 2, the first 10 terms will be:
#
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
## By considering the terms in the Fibonacci sequence whose values do not exceed
## four million, find the sum of the even-valued terms.

class Fibonacci
end

describe "problem two" do
  subject { Fibonacci.new }

  xit 'returns the sum of the even valued terms' do
    items = subject.take_while { |n| n < 4_000_000 }.find_all(&:even?)
    result = items.inject(0) { |memo, x| memo + x }
    expect(result).to eql(4613732)
  end
end
